-- Common config
require("plugins")
require("settings")
require("keybindings")

-- Plugins config
require("indent-blankline")
require("nv-gitsigns")
require("nv-lualine")
require("nv-tree")
require("nv-treesitter")
require("nv-lspinstall")
require("lsp-config")
require("nv-compe")
require("nv-comment")
require("vim-maximizer")
require("nv-telescope")
require("nv-todo-comments")
require("nv-zen-mode")
require("nv-trouble")
