require("plugins")
require("settings")
require("keybindings")

-- Plugins config
require("config.gruvbox")
require("config.nvim-comment")
require("config.git-gutter")
require("config.lualine")
require("config.indent-blankline")
require("config.nvim-tree")
require("config.tree-sitter")
require("config.nvim-lspinstall")
require("config.lsp-config")
require("config.nv-compe")
